### PR TITLE
feat(response-text): add response-text check

### PR DESCRIPTION
**Pull request by keithamus**
This check works similar to the json check, except that it just uses fetch's `text()` method
to parse the body.

This is needed for a check where the response is not JSON.

/cc @wheresrhys @ifyio

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Similar to https://github.com/Financial-Times/n-health/blob/master/src/checks/string.check.js ?

**Comment by keithamus** [comment]
Ahh, I didn't notice that one from the readme, but also I need the callback so I can parse the text (its in querystring format not json) to validate it.

**Comment by ironsidevsquincy** [comment]
Could you add that as an optional parameter for the string test (just saves on having many similar but slightly different checks)?

**Comment by keithamus** [comment]
yup will do

**Comment by wheresrhys** [comment]
If this goes in can you please add to the readme

**Pull request closed without merging**
